### ISSUE TITLE
click is not opening the options list

### ISSUE THREAD

**Issue by davidetruffo** [adamcoulombe/jquery.customSelect#37]
Sorry for the silly question, but I'm getting crazy on this.
I have a select coded from django, and i applied your plugin. It works fine for the style (perfectly i would say), but when i click on the select i get no option list. Any hint?
my html markup:

``` html
<select name="supplier" id="id_supplier" class="hasCustomSelect" style="width: 254px; position: absolute; opacity: 0; height: 28px; font-size: 12px;">
<option selected="selected" value="">---------</option>
</select>
<span class="customSelect" style="display: inline-block;">
<span class="customSelectInner" style="width: 236px; display: inline-block;">---------</span>
</span>
```

my js:

``` javascript
$('#id_supplier, #id_iva').customSelect();
```

my css:

``` css
.customSelect {
    /* Styles For Your Select Box */
    position: relative;
    background:url('/static/web/images/calendario.png') no-repeat 205px center;
    font-family:$_font_arial;
    font-size:12px;
}
.customSelect {
    border-radius:5px;
    border:2px solid $_blu_chiaro;
    padding:0 5px;
    margin:0 0 30px 30px;
    font-family:$_font_arial;
    font-size:12px;
        width:220px;
    height:25px;
}
```
